[Lab-5] API and state manager
sanloid/VasilchenkoAlexanderWebEffective pull request #7
Opened 2022-11-30 18:07 UTC by sanloid

Васильченко Александр

2022-12-03 19:18 UTC, annamyamikova requested changes
У меня нет вашего ключа, поэтому я запросы не получаю
.env хранится только локально. Не нужно было удалять файл .env.example. Создайте его и из файла .env перенесите все туда.

Не принято.

2022-12-07 19:49 UTC, konstantinzelinsky approved these changes
Принял, есть небольшие ошибки

2022-12-07 19:49 UTC, konstantinzelinsky commented on lab_3/react-ts-template/src/components/Pagination.tsx
> +  const activeStyle =
Эти строковые константы я бы вынес за пределы компонента, потому что они никак не зависят от его контекста, но при этом будут пересоздаваться при каждом ререндере

2022-12-07 19:49 UTC, konstantinzelinsky commented on lab_3/react-ts-template/src/stores/Store.ts
> +  Response: ResponsesTypes;
Переменные (в данном случае поле) принято называть с маленькой буквы

2022-12-07 19:49 UTC, konstantinzelinsky commented on lab_3/react-ts-template/src/stores/Store.ts
> +  OnPage: number = 9;
Переменные (в данном случае поле) принято называть с маленькой буквы

2022-12-07 19:49 UTC, konstantinzelinsky commented on lab_3/react-ts-template/src/stores/Store.ts
> +      runInAction(() => {
Здесь нет необходимости использовать runInAction

2022-12-07 19:49 UTC, merged